### ISSUE TITLE
Un tag ? ,)

### ISSUE THREAD

**Issue by francisbesset** [natsfr/SI1102_Breakout#1]
Chiche tu crées un tag du style v1.0.0 :D

**Comment by natsfr** [comment]
Rigole pas je sais pas faire ça :p
Je viens à peine d'apprendre les branches et ça me les brise déjà :D

**Comment by francisbesset** [comment]
T'inquiète ça vient au fur et à mesure :)

``` bash
$ git tag v1.0.0 92971062bcdf66caacb3030104a63ab0417a3015
$ git push origin v1.0.0
```

**Comment by hugokernel** [comment]
T'as mis un num de version sur le pcb ? En phase avec le tag ? ;)

**Comment by natsfr** [comment]
-_- bougez pas je vais chercher le fusil !!!
